networks:
  localnetwork:
    name: bookpricesjob_local
    driver: bridge
    attachable: true
services:
  api:
    build:
      context: ./
      dockerfile: Docker/api.Dockerfile
    image: dsp8ef9/bookprices_jobapi:latest
    env_file: Docker/api.env
    ports:
      - "8080:8080"
    networks:
      - localnetwork
  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - localnetwork
  db:
    image: mysql:8.4.0
    command: --mysql-native-password=ON
    restart: always
    env_file: Docker/db.env
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/db/data:/var/lib/mysql
    networks:
      - localnetwork

  dbmigration:
    build:
      context: ./
      dockerfile: Docker/dbmigration.Dockerfile
    image: dsp8ef9/bookprices_dbmigration:latest
    env_file: Docker/dbmigration.env
    networks:
      - localnetwork
