name: Docker Image Build and Push

on:
  push:
    branches: [ "main" ]

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and push BookPricesJob API
        uses: docker/build-push-action@v6
        with:
          file: Docker/api.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.API_DOCKER_IMAGE_NAME }}:latest

      - name: Build and push BookPricesJob DB Migration
        uses: docker/build-push-action@v6
        with:
          file: Docker/dbmigration.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DB_MIGRATION_DOCKER_IMAGE_NAME }}:latest
